function fig = plott(obj)
    %Raw data representation method
    %   Plots Kerr angle, first and second harmonics amplitudes and
    %   temperature as a function of time
    fig = Sagnatron.plot_time(obj.data, ...
        obj.fieldNames, ...
        'bin', obj.timeBin, ...
        'range', obj.timeRange, ...
        'showLegend', obj.showLegend, ...
        'verbose', obj.verbose);
    obj.timeFigure = fig;
end