function s = schema()
%Create and save table with instrument information for a given experiment.

    name =      ["tempcont";    "magnet";       "source";      "lockin";   ...
                 "lockinA";     "lockinB";      "lockinC";];
    driver =    ["LSCI331";     "KEPCO";        "Keithley2401"; "HF2LI"; ...
                 "SR830";       "SR830";        "SR830";];
    interface = ["gpib";        "gpib";         "gpib";         "ziDAQ"; ...
                 "gpib";        "gpib";         "gpib";];
    address =   [23;             5;              24;             18120;  ...
                12;              30;             14;];
    parameters = ...
                {{nan}; ...
                {nan}; ...
                {nan}; ...
                {}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}};
    fields =    {{'A', 'B'}; ...
                {'I', 'V'}; ...
                {'source', 'V', 'I'}; ...
                {'sample'}; ...
                {'X', 'Y', 'amplitude'}; ...
                {'X', 'Y'}; ...
                {'X', 'Y'}};

    s = table(name, driver, interface, address, parameters, fields);

    % Custom properties
    s = addprop(s,{'Seed', 'SourceFile', 'ExperimentDescription'}, {'table', 'table', 'table'});
    s.Properties.CustomProperties.SourceFile = string(mfilename('fullpath'));
    s.Properties.CustomProperties.ExperimentDescription = "Kerr, Resistance vs Magnetic field.";
end
