function s = schema()
%Create and save table with instrument information for a given experiment.

    name =      ["tempcont";     "lockin";   ...
                 "lockinA";     "lockinB"];
    driver =    ["LSCI331";      "HF2LI"; ...
                 "SR830";       "SR830"];
    interface = ["gpib";         "ziDAQ"; ...
                 "gpib";        "gpib"];
    address =   [23;             18120;  ...
                12;            30];
    parameters = ...
                {{nan}; ...
                {}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}};
    fields =    {{'A', 'B'}; ...
                {'sample'}; ...
                {'X', 'Y', 'amplitude', 'AUXV1'}; ...
                {'X', 'Y'}};

    s = table(name, driver, interface, address, parameters, fields);

    % Custom properties
    s = addprop(s,{'Seed', 'SourceFile', 'ExperimentDescription'}, {'table', 'table', 'table'});
    s.Properties.CustomProperties.SourceFile = string(mfilename('fullpath'));
    s.Properties.CustomProperties.ExperimentDescription = "Photgalv curr vs Gate voltage sweep.";
end
