function schema = schema(seed)
%Create and save table with instrument information
%   seed:
%        84 T -- LSCI331[23].
%       114 r -- SR830[12], LSCI331[23].
%       116 t -- SR830[12], SR830[30], LSCI331[23].
%       112 p -- Optical power
%       100 d -- DC voltage
%       119 w -- wavelength sweep on Optical power detector

if nargin < 1, fprintf("[make.schema] Please provide a seed/key."); return; end
key = make.key(seed);

switch key
    case 84     % 'T' Single temperature controller
        name =      "tempcont";
        driver =    "LSCI331";
        interface = "visa";
        address =   23;
        parameters = {{nan}};
        fields =    {{}};
        
    case 107    % 'k' Kerr (main)
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "tempcont";   "magnet"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "LSCI331";    "KEPCO"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "gpib";       "visa"];
        address =   [15;        19;         17;                 9;          23;           5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {nan}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {'A', 'B'}; ...
                     {}};
                 
    case 12412      %tk: Kerr effect (time only)
        name =      ["diode";   "waveform"; "voltmeter";        "lockin"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib"];
        address =   [15;        19;         17;                 9];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}};
                 
    case 14520      %xy: Kerr XY scan
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "X";    "Y"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "Agilis";   "Agilis"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "serial";   "serial"];    % FIXME
        address =   [15;        19;         17;                 9;          5;          6];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {nan}; ...
                     {nan}};
        fields =    {{}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {'position'}; ...
                     {'position'}};
                 
    case 120      %x: Kerr XY scan
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "X";    "Y"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "Agilis";   "Agilis"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "serial";   "serial"];    % FIXME
        address =   [15;        19;         17;                 9;          5;          6];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {nan}; ...
                     {nan}};
        fields =    {{}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {'position'}; ...
                     {'position'}};
                 
    case 11600     % td : dc voltage (time only)
        name =      ["diode";   "waveform"; "voltmeter";        "lockin"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib"];
        address =   [15;        19;         17;                 9];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}};
    
    case 121    %y: Hysteresis in Kerr signal
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "tempcont";   "magnet"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "LSCI331";    "KEPCO"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "gpib";       "visa"];
        address =   [15;        19;         17;                 9;          23;           5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {nan}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {'A', 'B'}; ...
                     {}};
                 
    case 105    %i: Laser intensity sweep
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "tempcont";   "magnet"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "LSCI331";    "KEPCO"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "gpib";       "visa"];
        address =   [15;        19;         17;                 9;          23;           5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {nan}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {nan}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {'A', 'B'}; ...
                     {}};
                 
    case 102    %f: Mod freq sweep
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "magnet"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "KEPCO"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "visa"];
        address =   [15;        19;         17;                 9;          5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {'freq', 'ampl'}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {}};
                 
    case 97    %a: Mod amplitude sweep
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "magnet"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "KEPCO"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "visa"];
        address =   [15;        19;         17;                 9;          5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {'freq', 'ampl'}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                     {}};
                 
    case 9894   %fa: Mod freq and amplitude sweep
        name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "magnet"];
        driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "KEPCO"];
        interface = ["gpib";    "gpib";     "gpib";             "gpib";     "visa"];
        address =   [15;        19;         17;                 9;          5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {nan}; ...
                     {}; ...
                     {}};
        fields =    {{}; ...
                     {'freq', 'ampl'}; ...
                     {'v1'}; ...
                     {'X', 'Y', 'R', 'Q'}; ...
                     {}};
        
    case 68     %D: Diode temperature
        name =      "diode";
        driver =    "ILX3724";
        interface = "visa";
        address =   15;
        parameters ={{}};
        fields =    {{'temperature', 'resistance'}};
        
    case 114    %r: Single transport lockin
        name =      "lockin";
        driver =    "SR830";
        interface = "visad";
        address =   30;
        parameters ={{}};
        fields =    {{'X', 'Y', 'R', 'Q'}};
        
    case 116    %t: Two transport lockins & temperature controller
        name =      ["lockinA"; "lockinB";  "tempcont"];
        driver =    ["SR830";   "SR830";    "LSCI331"];
        interface = ["visadev"; "visadev";  "visa"];
        address =   [12;        30;         23];
        parameters = ...
                    {{}; ...
                     {'frequency', 'phase', 'timeConstant'}; ...
                     {nan}};
        fields =    {{'X', 'Y', 'R', 'Q'}; ...
                     {'X', 'Y'}; ...
                     {}};
                 
    case 104    %h: Hall effect measurement
        name =      ["lockinA"; "lockinB";  "tempcont"; "magnet"];
        driver =    ["SR830";   "SR830";    "LSCI331";  "KEPCO"];
        interface = ["visa";    "visa";     "visa";     "visa"];
        address =   [12;        30;         23;         5];
        parameters = ...
                    {{}; ...
                     {}; ...
                     {}; ...
                     {}};
        fields =    {{'X', 'Y', 'R', 'Q'}; ...
                     {'X', 'Y'}; ...
                     {}; ...
                     {}};
                 
    case 112    %p: Optical power measurement with Newport 1830-C
        name =      ["diode";   "powermeter"];
        driver =    ["ILX3724"; "Newport1830"];
        interface = ["visa";    "gpib"];
        address =   [15;        13];
        parameters = ...
                    {{}; ...
                     {nan}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {}};
                 
    case 100    %d: DC voltage with Keithley 2182A
        name =      ["diode";   "voltmeter"];
        driver =    ["ILX3724"; "Keithley2182A"];
        interface = ["visa";    "gpib"];
        address =   [15;        17];
        parameters = ...
                    {{}; ...
                     {nan}};
        fields =    {{'current', 'voltage', 'temperature'}; ...
                     {'v1'}};
    
    case 119    %w: wavelength sweep Newport 1830-C
        name =      ["diode";   "powermeter"];
        driver =    ["ILX3724"; "Newport1830"];
        interface = ["visa";    "gpib"];
        address =   [15;        13];
        parameters = ...
                    {{}; ...
                     {nan}};
        fields =    {{'current'}; ...
                     {'wavelength', 'power'}};
                 
    case {11960, make.key('hs:')}    % Hall sensor
        name =      ["magnet";  "voltmeter"];
        driver =    ["KEPCO";   "Keithley2182A"];
        interface = ["visa";    "gpib"];
        address =   [5;         17];
        parameters = ...
                    {{}; ...
                     {nan}};
        fields =    {{'I', 'V'}; ...
                     {'v1'}};
                 
    case 117    % 'u'
        %Do nothing. User will create schema.
        schema = table();
        return
    otherwise
        disp("[make.schema] Unkown experiment configuration.");
        name =      "tempcont";
        driver =    "LSCI331";
        interface = "visa";
        address =   23;
        parameters = {{nan}};
        fields =    {{}};
end

schema = table(name, driver, interface, address, parameters, fields);
writetable(schema, sprintf("schema-%d.csv", key));
