function s = schema()
%Create and save table with instrument information for a given experiment.

    name =      ["tempcont";     "source";      "lockin";   ...
                  "waveplate";  ...
                 "lockinA";     "lockinB";      "lockinC";];
    driver =    ["LSCI331";      "Keithley2401";    "HF2LI"; ...
                "Kinesis10CR2"; ...
                 "SR830";       "SR830";        "SR830";];
    interface = ["gpib";         "gpib";        "ziDAQ"; ...
                 "Kinesis"; ...
                 "gpib";        "gpib";         "gpib";];
    address =   [23;              24;           18120;  ...
                 NaN; ...
                12;            30;             14;];
    parameters = ...
                {{nan}; ...
                {nan}; ...
                {}; ...
                {}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}; ...
                {'amplitude', 'phase', 'frequency', 'timeConstant'}};
    fields =    {{'A', 'B'}; ...
                {'source', 'V', 'I'}; ...
                {'sample'}; ...
                {'angle'}; ...
                {'X', 'Y', 'amplitude'}; ...
                {'X', 'Y'}; ...
                {'X', 'Y'}};

    s = table(name, driver, interface, address, parameters, fields);

    % Custom properties
    s = addprop(s,{'Seed', 'SourceFile', 'ExperimentDescription'}, {'table', 'table', 'table'});
    s.Properties.CustomProperties.SourceFile = string(mfilename('fullpath'));
    s.Properties.CustomProperties.ExperimentDescription = "Resistance vs Waveplate orientation.";
end
