function fig = plot(obj)
    %Raw data representation method
    %   Plots Kerr angle, first and second harmonics amplitudes as
    %   a function of temperature
    fig = Sagnatron.plot_temperature(obj.data, ...
        obj.fieldNames, ...
        'bin', obj.tempBin, ...
        'range', obj.tempRange, ...
        'showLegend', obj.showLegend, ...
        'verbose', obj.verbose);
    obj.tempFigure = fig;
end  