function schema = k()
%Create and save table with instrument information for a given experiment.

    name =      ["diode";   "waveform"; "voltmeter";        "lockin";   "tempcont";   "magnet"];
    driver =    ["ILX3724"; "A33220A";  "Keithley2182A";    "SR844";    "LSCI331";    "KEPCO"];
    interface = ["gpib";    "gpib";     "gpib";             "gpib";     "gpib";       "visa"];
    address =   [15;        19;         17;                 9;          23;           5];
    parameters = ...
                {{}; ...
                {}; ...
                {nan}; ...
                {}; ...
                {nan}; ...
                {}};
    fields =    {{nan}; ...
                {nan}; ...
                {'v1'}; ...
                {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                {'A', 'B'}; ...
                {}};

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
