function schema = xy()
%Create and save table with instrument information for a given experiment.

    name =      ["voltmeter";        "lockin";   "X";       "Y"];
    driver =    ["Keithley2182A";    "SR844";    "Agilis";  "Agilis"];
    interface = ["gpib";             "gpib";     "serial";  "serial"];
    address =   [17;                 9;          5;         6];
    parameters = ...
                {{nan}; ...
                {nan}; ...
                {nan}; ...
                {nan}};
    fields =    {{'v1'}; ...
                {'X', 'Y', 'R', 'Q', 'AUX1', 'AUX2'}; ...
                {'position'}; ...
                {'position'}};

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
