function schema = zbo()
%Create and save table with instrument information for a given experiment.

    name =      ["voltmeter";        "lockin";      "bcb"];
    driver =    ["Keithley2182A";    "HF2LI";       "BCB"];
    interface = ["gpib";             "ziDAQ";       "serial"];
    address =   [ 17;                 18120;        8];
    parameters = { ...
                {nan}; ...
                {}; ...
                {'mode', 'vpi'} ...
                };
    fields =    { ...
                {'v1'}; ...
                {'x', 'y'}; ...
                {'voltage', 'optical_power'} ...
                };

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
