function schema = zi()
%Create and save table with instrument information for a given experiment.

    name =      ["diode";       "voltmeter";        "lockin";];
    driver =    ["ILX3724";     "Keithley2182A";    "HF2LI";];
    interface = ["gpib";        "gpib";             "ziDAQ";];
    address =   [ 15;            17;                 18120;];
    parameters = { ...
                {nan}; ...
                {nan}; ...
                {} ...
                };
    fields =    { ...
                {'I'}
                {'v1'}; ...
                {'x', 'y'}; ...
                };

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
