function schema = zkg()
%Create and save table with instrument information for a given experiment.

    name =      ["voltmeter"; "lockin";   "tempcont"; 
                "source";   "lockinA";   "lockinB"];
    driver =    ["Keithley2182A"; "HF2LI";    "LSCI331";   ...
                "Keithley2401"; "SR830"; "SR830"];
    interface = ["gpib";    "ziDAQ";    "gpib";   ...
                "gpib";    "gpib";     "gpib"];
    address =   [17;        18120;         23;  ...
                24;        12;         30];
    parameters = ...
            {{nan}; ...
            {nan}; ...
            {nan}; ...
            {nan}; ...
            {nan}; ...
            {nan}};
    fields =    {{'v1'}; ...
                {'x', 'y'}; ...
                {'A', 'B'}; ...
                {'source', 'V', 'I'}; ...
                {'X', 'Y'}; ...
                {'X', 'Y'}};

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
