function schema = zkr()
%Create and save table with instrument information for a given experiment.

    name =      ["voltmeter";        "lockin";      "tempcont";     "lockinA"];
    driver =    ["Keithley2182A";    "HF2LI";       "LSCI331";      "SR830"];
    interface = ["gpib";             "ziDAQ";       "gpib";         "visa"];
    address =   [ 17;                 18120;         23;            "12"];
    parameters = ...
                {{nan}; ...
                {}; ...
                {nan}; ...
                {nan}};
    fields =    {{'v1'}; ...
                {'x', 'y'}; ...
                {'A', 'B'}; ...
                {'X', 'Y'}};

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
