function schema = zy()
%Create and save table with instrument information for a given experiment.

    name =      ["voltmeter";        "lockin";   "tempcont";   "magnet"];
    driver =    ["Keithley2182A";    "HF2LI";    "LSCI331";    "KEPCO"];
    interface = ["gpib";             "ziDAQ";     "gpib";       "visa"];
    address =   [17;                 18120;          23;           5];
    parameters = ...
                {{nan}; ...
                {}; ...
                {nan}; ...
                {}};
    fields =    {{'v1'}; ...
                {'x', 'y'}; ...
                {'A', 'B'}; ...
                {'I'}};

    schema = table(name, driver, interface, address, parameters, fields);
    schema.Properties.Description = mfilename;
end
